services:
  postgres:
    networks:
      - msf
    container_name: postgres
    volumes:
      - ${HOME}/.msf4/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=msf
    image: postgres:11-alpine

  metasploit-framework:
    privileged: true
    stdin_open: true
    tty: true
    networks:
      msf:
        ipv4_address: 172.18.0.3
    container_name: msf
    environment:
      - DATABASE_URL=postgres://postgres:postgres@172.18.0.2:5432/msf
      - MSF_UID=1000  # Set Metasploit's user ID
      - MSF_GID=1000  # Set Metasploit's group ID
      - NMAP_PRIVILEGED=True
    volumes:
      - ${HOME}/.msf4:/home/msf/.msf4
      - ${HOME}/metasploit_data:/home/msf/metasploit_data
    ports:
      - "8443-8500:8443-8500"
      - "55552:55552"
    image: metasploitframework/metasploit-framework
    command: >
      sh -c "
      ./msfrpcd -P Rn4klU6y -f -a 0.0.0.0 -p 55552;
      tail -f /dev/null
      "

networks:
  msf:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

